### ISSUE TITLE
Put this snippet as a function (def) and call that function from __main__

### ISSUE THREAD

**Issue by sanjaypradeep** [sanjaypradeep/Python-Data-Structure#3]
https://github.com/sanjaypradeep/Python-Data-Structure/blob/d98edb763f59d3ffda0bbfe0dd0de2ce84a18dc3/Collections/WordOrder.py#L58

**Comment by atharvathombre** [comment]
Actually, i am a beginner in opensource contribution. I am not understanding what you are trying to say. Can you make me understand the issue more clear?

**Comment by ConnectNitish** [comment]
I would like to contribute to this snippet.

**Comment by sanjaypradeep** [comment]
@atharvathombre Thanks for contacting. I was try to say like - If you see the code snippet, there's a loop and conditional check happening, all these functionality should be inside a function.
